nodeLinker: node-modules

packageExtensions:
  "@nuxt/types@*":
    peerDependencies:
      webpack: "*"
  "@nuxt/typescript-build@*":
    peerDependencies:
      webpack: "*"
  "@nuxtjs/eslint-config-typescript@*":
    peerDependencies:
      eslint: "*"
  jest@*:
    peerDependencies:
      "@babel/core": "*"
  web3-provider-engine@*:
    peerDependencies:
      "@babel/core": "*"
  "@walletconnect/web3-provider@*":
     peerDependencies:
       "@babel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
